name: current_context
description: A Flutter package that allows you to access translated message without having to pass context.
version: 0.0.1
repository: https://github.com/Navideck/current_context

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: